name: Run repoCleaner (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      delete_all_branches:
        description: 'Delete all stale branches? (yes/no)'
        required: true
        default: 'no'
      delete_selected_branches:
        description: 'Enter the branch numbers to delete, separated by commas (or leave empty to skip)'
        required: false
        default: ''

jobs:
  run-repoCleaner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run repoCleaner script
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        DELETE_ALL_BRANCHES: ${{ github.event.inputs.delete_all_branches }}
        DELETE_SELECTED_BRANCHES: ${{ github.event.inputs.delete_selected_branches }}
      run: |
        python repoCleaner.py  # This will now read the token and input from the environment
