name: Run repoCleaner

on:
  workflow_dispatch:  # Manual trigger event

jobs:
  run-repoCleaner:
    runs-on: ubuntu-latest  # This is for an Ubuntu runner; you can switch to macOS or Windows if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.1'  # Use the latest stable Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run repoCleaner script
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_SECRET }}  # Access token from secrets
      run: |
        python3 repoCleaner.py
